# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8f94c0b8c81ba485bdf94dae04c9efd2c3b93c08e4b79a0460d8e1fd7a2ecb9dadcf268ae779e323c01907c13eba43b4e687b73dcc7ce8a3f7f68ee0647b958

test:
  secret_key_base: f680f1a144e88f6896a0535aa4a447ea0416838731b8b90fac972b68a8b8c6e06113e82cedaf558e5aac718fda0a5632fd243ef25998b85f0ac03305b5668622

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
